### ISSUE TITLE
change like method  not to equal,example sql method,%like%

### ISSUE THREAD

**Issue by picassogithub** [Jakiboy/SQL-it#1]
case 'like': // int|string
     if(strpos($source,$search) !== false)
     $this->data[$key] = $this->db[$key];
      break;

**Comment by picassogithub** [comment]
change tests index.php namespace,to 
use floatPHP\Arrays\SQLit;

**Comment by picassogithub** [comment]
good job,it's a amazing code,it's very helpful for me

**Comment by Jakiboy** [comment]
Thankyou  :)
